import os

import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

ORIGINAL_FILE = "original_explanation_result.wav"  # File generated by explain_audio.py
EXPLANATION_FILE = "explanation_result.wav"  # File generated by explain_audio.py
OUTPUT_IMAGE = "explanation_report.png"  # Output filename


def visualize_results():
    if not os.path.exists(ORIGINAL_FILE) or not os.path.exists(EXPLANATION_FILE):
        print("Error: Audio files not found. Please run 'explain_audio.py' first.")
        return

    print("Loading audio files...")
    y_orig, sr = librosa.load(ORIGINAL_FILE, sr=None)
    y_expl, sr = librosa.load(EXPLANATION_FILE, sr=None)

    # Ensure equal length (trim to shorter one if necessary)
    min_len = min(len(y_orig), len(y_expl))
    y_orig = y_orig[:min_len]
    y_expl = y_expl[:min_len]

    # Calculate Residual (Original minus Artifacts)
    # This represents the "Clean" signal theoretically
    y_residual = y_orig - y_expl

    print("Generating spectrograms...")

    # Helper function for Mel-Spectrogram (dB scale)
    def get_spec(y):
        # n_mels=128 gives good resolution for EnCodec features
        S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128, fmax=12000)
        S_dB = librosa.power_to_db(S, ref=np.max)
        return S_dB

    S_orig = get_spec(y_orig)
    S_expl = get_spec(y_expl)
    S_resid = get_spec(y_residual)

    fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(14, 10))
    plt.subplots_adjust(hspace=0.3, wspace=0.2)

    # Original
    ax1 = axes[0, 0]
    img1 = librosa.display.specshow(
        S_orig, x_axis="time", y_axis="mel", sr=sr, fmax=12000, ax=ax1, cmap="magma"
    )
    ax1.set_title("A. Original Input (Test Sample)", fontsize=12, fontweight="bold")
    ax1.set_xlabel("")
    plt.colorbar(img1, ax=ax1, format="%+2.0f dB")

    # Explanation (artifacts)
    ax2 = axes[0, 1]
    img2 = librosa.display.specshow(
        S_expl, x_axis="time", y_axis="mel", sr=sr, fmax=12000, ax=ax2, cmap="jet"
    )
    ax2.set_title(
        "B. Generated Explanation (Artifacts Only)", fontsize=12, fontweight="bold"
    )
    ax2.set_xlabel("")
    ax2.set_ylabel("")
    plt.colorbar(img2, ax=ax2, format="%+2.0f dB")

    # Overlay
    ax3 = axes[1, 0]
    # Plot Original in Grayscale
    librosa.display.specshow(
        S_orig,
        x_axis="time",
        y_axis="mel",
        sr=sr,
        fmax=12000,
        ax=ax3,
        cmap="gray_r",
        alpha=0.6,
    )

    # Plot Explanation on top (Masking silence/low energy)
    # We mask everything below -60dB so the background remains visible
    S_expl_masked = np.ma.masked_where(S_expl < -60, S_expl)
    img3 = librosa.display.specshow(
        S_expl_masked,
        x_axis="time",
        y_axis="mel",
        sr=sr,
        fmax=12000,
        ax=ax3,
        cmap="jet",
        alpha=0.7,
    )

    ax3.set_title("C. Artifact Localization (Overlay)", fontsize=12, fontweight="bold")
    plt.colorbar(img3, ax=ax3, format="%+2.0f dB")

    # Residual - original without artifacts
    ax4 = axes[1, 1]
    img4 = librosa.display.specshow(
        S_resid, x_axis="time", y_axis="mel", sr=sr, fmax=12000, ax=ax4, cmap="viridis"
    )
    ax4.set_title(
        "D. Residual Signal (Original - Artifacts)", fontsize=12, fontweight="bold"
    )
    ax4.set_ylabel("")
    plt.colorbar(img4, ax=ax4, format="%+2.0f dB")

    plt.suptitle(
        "Qualitative Analysis of Deepfake Attribution (AudioXgen Method)", fontsize=16
    )
    plt.savefig(OUTPUT_IMAGE, dpi=300, bbox_inches="tight")
    print(f"Success! Visualization saved as: {OUTPUT_IMAGE}")


if __name__ == "__main__":
    visualize_results()
